export const QATASK_LIST_REQUEST = "QATASK_LIST_REQUEST";
export const QATASK_LIST_SUCCESS = "QATASK_LIST_SUCCESS";
export const QATASK_LIST_FAIL = "QATASK_LIST_FAIL";

export const QATASK_CREATE_REQUEST = "QATASK_CREATE_REQUEST";
export const QATASK_CREATE_SUCCESS = "QATASK_CREATE_SUCCESS";
export const QATASK_CREATE_FAIL = "QATASK_CREATE_FAIL";

export const ADMIN_LIST_REQUEST = "ADMIN_LIST_REQUEST";
export const ADMIN_LIST_SUCCESS = "ADMIN_LIST_SUCCESS";
export const ADMIN_LIST_FAIL = "ADMIN_LIST_FAIL";

export const ADMIN_TASK_UPDATE_REQUEST = "ADMIN_TASK_UPDATE_REQUEST";
export const ADMIN_TASK_UPDATE_SUCCESS = "ADMIN_TASK_UPDATE_SUCCESS";
export const ADMIN_TASK_UPDATE_FAIL = "ADMIN_TASK_UPDATE_FAIL";
